---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-worker
spec:
  chartRef:
    kind: OCIRepository
    name: tdarr-worker
  interval: 1h
  values:
    controllers:
      nvidia-worker:
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr
              tag: 2.54.01@sha256:a1bcb1739e5355f41f2f9b9006040d6b27987e4d62aec15e7c161fe8833da27d
            command:
              # bypass supervisor
              - /usr/bin/node
            args:
              - --max-old-space-size=16384
              - /app/Tdarr_Node/srcug/main.js
            env:
              TZ: Australia/Melbourne
              healthcheckcpuWorkers: 4
              healthcheckgpuWorkers: 0
              inContainer: true
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              serverIP: tdarr.media.svc.cluster.local
              serverPort: 8266
              transcodecpuWorkers: 0
              transcodegpuWorkers: 2
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 8Gi
                nvidia.com/gpu: 1
    defaultPodOptions:
      runtimeClassName: nvidia
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        runAsGroup: 1000
    persistence:
      media:
        type: nfs
        server: 192.168.42.20
        path: /mnt/Slow/Media/Plex Media
      transcode:
        type: emptyDir
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
            subPath: logs
          - path: /app/configs
            subPath: configs
          - path: /app/Tdarr_Node/assets/app/plugins
            subPath: plugins
          - path: /tmp
            subPath: tmp
