---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
# Account 1:
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hydaz-com
spec:
  dnsNames:
    - hydaz.com
    - "*.hydaz.com"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: hydaz-com-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
# Account 2:
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hyde-services
spec:
  dnsNames:
    - hyde.services
    - "*.hyde.services"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: hyde-services-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${D_HCA//./-}
spec:
  dnsNames:
    - ${D_HCA}
    - "*.${D_HCA}"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ${D_HCA//./-}-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imagegenius-io
spec:
  dnsNames:
    - imagegenius.io
    - "*.imagegenius.io"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: imagegenius-io-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${D_SN//./-}
spec:
  dnsNames:
    - ${D_SN}
    - "*.${D_SN}"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ${D_SN//./-}-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${D_TACA//./-}
spec:
  dnsNames:
    - ${D_TACA}
    - "*.${D_TACA}"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ${D_TACA//./-}-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${D_TAN//./-}
spec:
  dnsNames:
    - ${D_TAN}
    - "*.${D_TAN}"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ${D_TAN//./-}-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
# Account 3:
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${D_LMVCA//./-}
spec:
  dnsNames:
    - ${D_LMVCA}
    - "*.${D_LMVCA}"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ${D_LMVCA//./-}-tls
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${D_BBPC//./-}
spec:
  dnsNames:
    - ${D_BBPC}
    - "*.${D_BBPC}"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: ${D_BBPC//./-}-tls
  usages:
    - digital signature
