---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chartRef:
    kind: OCIRepository
    name: nextcloud
  interval: 1h
  values:
    controllers:
      nextcloud:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          copy-config:
            image: &image
              repository: docker.io/library/nextcloud
              tag: 32.0.6@sha256:0e1084cc59df77bec7d6bb29d9ac6939da8372512237a9c51f74ff0a970524f2
            command:
              - sh
              - -c
              - "cp -r /usr/src/nextcloud/config/*.php /var/www/html/config/"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
        containers:
          app:
            image: *image
            env:
              NEXTCLOUD_TRUSTED_DOMAINS: storage.hyde.services
              NEXTCLOUD_DATA_DIR: /var/www/html/data
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status.php
                    port: &port 80
                    httpHeaders:
                      - name: Host
                        value: storage.hyde.services
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 15m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          # use gatus to run cron jobs (imo least jank method)
          gatus.home-operations.com/endpoint: |-
            url: https://storage.hyde.services/cron.php
        hostnames:
          - storage.hyde.services
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  add:
                    - name: Strict-Transport-Security
                      value: "max-age=31536000; includeSubDomains; preload"
    configMaps:
      config:
        data:
          custom.config.php: |-
            <?php
            $CONFIG = array(
            	'overwriteprotocol' => 'https',
            	'overwrite.cli.url' => 'https://storage.hyde.services',
            	'overwritehost' => 'storage.hyde.services',
            	'check_data_directory_permissions' => false,
            	'default_phone_region' => 'AU',
            	'trusted_proxies' => array(
            		0 => '127.0.0.1',
            		1 => '10.42.0.0/16',
            	),
            	'trusted_domains' => array(
            		0 => '127.0.0.1',
            		1 => 'storage.hyde.services',
            	),
            	'simpleSignUpLink.shown' => false,
            	'cache_path' => '/cache',
            	'forwarded_for_headers' => array('X-Forwarded-For'),
            	'maintenance_window_start' => 100,
            	'memcache.distributed' => '\OC\Memcache\Redis',
            	'memcache.locking' => '\OC\Memcache\Redis',
            	'redis' => array(
            		'host' => 'dragonfly.databases.svc.cluster.local',
            		'port' => 6379,
            		'dbindex' => 1,
            	),
            );
          php.ini: |-
            session.save_handler = redis
            session.save_path = "tcp://dragonfly.databases.svc.cluster.local:6379/1"
            redis.session.locking_enabled = 1
            redis.session.lock_retries = -1
            redis.session.lock_wait_time = 10000
            upload_max_filesize = 16G
            post_max_size = 16G
            memory_limit = 512M
            max_execution_time = 3600
          www.conf: |-
            [www]
            listen = 127.0.0.1:9000
            pm = dynamic
            pm.max_children = 50
            pm.start_servers = 12
            pm.min_spare_servers = 6
            pm.max_spare_servers = 18
          remoteip.conf: |-
            RemoteIPHeader X-Forwarded-For
            RemoteIPInternalProxy 10.42.0.0/16
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/www/html
      alex-nfs:
        type: nfs
        server: 192.168.42.20
        path: /mnt/Fast/Alex
        globalMounts:
          - path: /var/www/html/data/alex/files
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /var/www/html/config/custom.config.php
            subPath: custom.config.php
          - path: /usr/local/etc/php/conf.d/php.ini
            subPath: php.ini
          - path: /usr/local/etc/php-fpm.d/www.conf
            subPath: www.conf
          - path: /etc/apache2/conf-available/remoteip.conf
            subPath: remoteip.conf
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /cache
            subPath: cache
          - path: /var/run
            subPath: run
